version: '3.7'
services:    
    skeleton-group-activity-recognition:
       build:
             context: ./
             target: skeleton-group-activity-recognition
       container_name: skeleton-group-activity-recognition
       image: skeleton-group-activity-recognition:latest
       volumes:
           - type: bind
             source: /tmp/.X11-unix # for img show. run xhost + before run the container
             target: /tmp/.X11-unix # for img show. run xhost + before run the container

           - type: bind
             source: ./
             target: /work/sk-gar

       stdin_open: true # docker run -i
       tty: true # docker run -t
       ipc: host
       network_mode: 'host'
       
       runtime: nvidia # for gpu
       environment:
           - NVIDIA_VISIBLE_DEVICES=all # for gpu
           - DISPLAY=$DISPLAY # for img show. run xhost + before run the container


    tesi-magistrale-openpose:
      build:
        context: ./
        target: openpose
      container_name: openpose
      image: openpose:latest
      volumes:
        - type: bind
          source: /tmp/.X11-unix # for img show. run xhost + before run the container
          target: /tmp/.X11-unix # for img show. run xhost + before run the container

        - type: bind
          source: ./SkeletonGroupActivityRecognition
          target: /work/sk-gar

      stdin_open: true # docker run -i
      tty: true # docker run -t
      ipc: host
      network_mode: 'host'

      runtime: nvidia # for gpu
      environment:
        - NVIDIA_VISIBLE_DEVICES=all # for gpu
        - DISPLAY=$DISPLAY # for img show. run xhost + before run the container
